FROM nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
# FROM python:3

# COPY ./requirements.txt /requirements.txt

# WORKDIR /

# RUN pip install -r requirements.txt

# COPY . /

# ENTRYPOINT [ "python3" ]

# CMD [ "Loader1.py" ]
